if File.exist?(".env")
  File.foreach(".env") do |line|
	  next if line.strip.empty? || line.start_with?("#")
	  key, value = line.strip.split('=', 2)
	  ENV[key] = value.gsub(/\A['"]|['"]\z/, '')
  end
end


ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

NODES = {
  "target-node" => { hostname: "runner",     ip: "192.168.56.10", memory: 1024, cpus: 1 },
  "vpn-node" => { hostname: "production", ip: "192.168.56.11", memory: 1024, cpus: 1 },
}


Vagrant.configure("2") do |config|
  config.vm.box          = "bento/ubuntu-24.04"
  config.vm.boot_timeout = 300

  config.vm.synced_folder ".", "/vagrant", disabled: true    

  NODES.each do |name, cfg|
	  config.vm.define name do |node|
		  node.vm.hostname = cfg[:hostname]
		  node.vm.network "private_network", ip: cfg[:ip]

		  # Libvirt (Linux host)
		  node.vm.provider "libvirt" do |lv|
			  lv.memory            = cfg[:memory]
			  lv.cpus              = cfg[:cpus]
			  lv.storage_pool_name = "images"
		  end
	  
		  # VirtualBox (Windows host)
		  node.vm.provider "virtualbox" do |vb|
			  vb.memory       = cfg[:memory]
			  vb.cpus         = cfg[:cpus]
			  vb.linked_clone = true
		  end

		  if name == "target-node"
			  node.vm.provision "configure_target", type: "shell" do |s|
					  s.inline = <<~SHELL
					  sudo mkdir -p /app/nginx  \
						  && sudo chown -R vagrant:vagrant /app

            if ! command -v docker &> /dev/null; then
                sudo DEBIAN_FRONTEND=noninteractive apt-get update &>/dev/null \
                    && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker.io &>/dev/null
            fi

            tee /app/nginx/nginx.conf <<'EOF'
upstream target_service {
    server localhost:8080;
}

server {
    listen 80;

    location /target-service {
        allow 192.168.56.11; # vpn node IP
        deny all;            # Все остальные мимо
        proxy_pass http://target_service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }    
}
EOF
						if sudo docker ps -a | grep "target-service"; then
							sudo docker rm -f target-service
						fi
            sudo docker run -d -p 8080:80 \ 
							--name target-service kennethreitz/httpbin

						if sudo docker ps -a | grep "nginx-service"; then
							sudo docker rm -f nginx-service
						fi
            sudo docker run -d -p 80:80 \ 
							-v /app/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro \ 
							--network host --name nginx nginx:alpine
				  SHELL
			  end
		  end

		  if name == "vpn-node"
			  # node.vm.provision "make_app_dir", type: "shell" do |s|
				#   s.inline = <<~SHELL
				#   SHELL
			  # end

			  node.vm.provision "configure_vpn", type: "shell" do |s|
				  s.path   = "scripts/xray-init.sh.tpl"
				  s.binary = true
				  s.env    = {}
			  end
		  end
	  end
  end
end
