name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init / Apply
        run: |
          terraform init
          terraform apply --auto-approve

      - name: Wait for user_data to finish
        run: sleep 90

      - name: Get WireGuard client config from SSM
        run: |
          aws ssm get-parameter \
            --name "/vpn/client-config" \
            --with-decryption \
            --query Parameter.Value \
            --output text > wg0-client.conf

      - name: Upload WireGuard config
        uses: actions/upload-artifact@v4
        with:
          name: wg-config
          path: wg0-client.conf

      - name: Upload Terraform state
        uses: actions/upload-artifact@v4
        with:
          name: tfstate
          path: terraform.tfstate
